export const citys = [
  { id: 1, city: "台北市" },
  { id: 2, city: "新北市" },
  { id: 3, city: "新竹縣" },
  { id: 4, city: "新竹市" },
  { id: 5, city: "新竹科學園區" },
  { id: 6, city: "苗栗縣" },
  { id: 7, city: "台中市" },
  { id: 8, city: "嘉義市" },
  { id: 9, city: "台南市" },
  { id: 10, city: "高雄市" },
  { id: 11, city: "屏東縣" },
];

export const options = [
  { id: 1, city: 1, district: "松山區" },
  { id: 2, city: 1, district: "信義區" },
  { id: 3, city: 1, district: "大安區" },
  { id: 4, city: 1, district: "中山區" },
  { id: 5, city: 1, district: "中正區" },
  { id: 6, city: 1, district: "大同區" },
  { id: 7, city: 1, district: "萬華區" },
  { id: 8, city: 1, district: "文山區" },
  { id: 9, city: 1, district: "南港區" },
  { id: 10, city: 1, district: "內湖區" },
  { id: 11, city: 1, district: "士林區" },
  { id: 12, city: 1, district: "北投區" },
  { id: 13, city: 2, district: "八里區" },
  { id: 14, city: 2, district: "三芝區" },
  { id: 15, city: 2, district: "三重區" },
  { id: 16, city: 2, district: "三峽區" },
  { id: 17, city: 2, district: "土城區" },
  { id: 18, city: 2, district: "中和區" },
  { id: 19, city: 2, district: "五股區" },
  { id: 20, city: 2, district: "永和區" },
  { id: 21, city: 2, district: "石門區" },
  { id: 22, city: 2, district: "石碇區" },
  { id: 23, city: 2, district: "汐止區" },
  { id: 24, city: 2, district: "金山區" },
  { id: 25, city: 2, district: "林口區" },
  { id: 26, city: 2, district: "坪林區" },
  { id: 27, city: 2, district: "板橋區" },
  { id: 28, city: 2, district: "泰山區" },
  { id: 29, city: 2, district: "淡水區" },
  { id: 30, city: 2, district: "深坑區" },
  { id: 31, city: 2, district: "萬里區" },
  { id: 32, city: 2, district: "瑞芳區" },
  { id: 33, city: 2, district: "新店區" },
  { id: 34, city: 2, district: "新莊區" },
  { id: 35, city: 2, district: "樹林區" },
  { id: 36, city: 2, district: "雙溪區" },
  { id: 37, city: 2, district: "蘆洲區" },
  { id: 38, city: 2, district: "鶯歌區" },
  { id: 39, city: 3, district: "竹北市" },
  { id: 40, city: 3, district: "竹東鎮" },
  { id: 41, city: 3, district: "湖口鄉" },
  { id: 42, city: 3, district: "新豐鄉" },
  { id: 43, city: 4, district: "東區" },
  { id: 44, city: 4, district: "北區" },
  { id: 45, city: 4, district: "香山區" },
  { id: 46, city: 5, district: "新竹科學園區" },
  { id: 47, city: 6, district: "竹南鎮" },
  { id: 48, city: 6, district: "苑裡鎮" },
  { id: 49, city: 7, district: "中區" },
  { id: 50, city: 7, district: "東區" },
  { id: 51, city: 7, district: "西區" },
  { id: 52, city: 7, district: "南區" },
  { id: 53, city: 7, district: "北區" },
  { id: 54, city: 7, district: "西屯區" },
  { id: 55, city: 7, district: "南屯區" },
  { id: 56, city: 7, district: "北屯區" },
  { id: 57, city: 7, district: "豐原區" },
  { id: 58, city: 7, district: "大里區" },
  { id: 59, city: 7, district: "太平區" },
  { id: 60, city: 7, district: "清水區" },
  { id: 61, city: 7, district: "沙鹿區" },
  { id: 62, city: 7, district: "大甲區" },
  { id: 63, city: 7, district: "東勢區" },
  { id: 64, city: 7, district: "梧棲區" },
  { id: 65, city: 7, district: "烏日區" },
  { id: 66, city: 7, district: "神岡區" },
  { id: 67, city: 7, district: "大肚區" },
  { id: 68, city: 7, district: "大雅區" },
  { id: 69, city: 7, district: "后里區" },
  { id: 70, city: 7, district: "霧峰區" },
  { id: 71, city: 7, district: "潭子區" },
  { id: 72, city: 7, district: "龍井區" },
  { id: 73, city: 7, district: "外埔區" },
  { id: 74, city: 7, district: "和平區" },
  { id: 75, city: 7, district: "石岡區" },
  { id: 76, city: 7, district: "大安區" },
  { id: 77, city: 7, district: "新社區" },
  { id: 78, city: 8, district: "市區" },
  { id: 79, city: 9, district: "七股區" },
  { id: 80, city: 9, district: "下營區" },
  { id: 81, city: 9, district: "山上區" },
  { id: 82, city: 9, district: "中西區" },
  { id: 83, city: 9, district: "仁德區" },
  { id: 84, city: 9, district: "六甲區" },
  { id: 85, city: 9, district: "北門區" },
  { id: 86, city: 9, district: "北區" },
  { id: 87, city: 9, district: "永康區" },
  { id: 88, city: 9, district: "玉井區" },
  { id: 89, city: 9, district: "白河區" },
  { id: 90, city: 9, district: "安平區" },
  { id: 91, city: 9, district: "安南區" },
  { id: 92, city: 9, district: "佳里區" },
  { id: 93, city: 9, district: "官田區" },
  { id: 94, city: 9, district: "東山區" },
  { id: 95, city: 9, district: "東區" },
  { id: 96, city: 9, district: "南區" },
  { id: 97, city: 9, district: "後壁區" },
  { id: 98, city: 9, district: "柳營區" },
  { id: 99, city: 9, district: "麻豆區" },
  { id: 100, city: 9, district: "善化區" },
  { id: 101, city: 9, district: "新化區" },
  { id: 102, city: 9, district: "新市區" },
  { id: 103, city: 9, district: "新營區" },
  { id: 104, city: 9, district: "歸仁區" },
  { id: 105, city: 9, district: "關廟區" },
  { id: 106, city: 9, district: "鹽水區" },
  { id: 107, city: 10, district: "新興區" },
  { id: 108, city: 10, district: "苓雅區" },
  { id: 109, city: 10, district: "三民區" },
  { id: 110, city: 10, district: "鹽埕區" },
  { id: 111, city: 10, district: "前金區" },
  { id: 112, city: 10, district: "鳳山區" },
  { id: 113, city: 10, district: "左營區" },
  { id: 114, city: 10, district: "前鎮區" },
  { id: 115, city: 10, district: "鼓山區" },
  { id: 116, city: 10, district: "楠梓區" },
  { id: 117, city: 10, district: "旗津區" },
  { id: 118, city: 10, district: "小港區" },
  { id: 119, city: 10, district: "梓官區" },
  { id: 120, city: 10, district: "仁武區" },
  { id: 121, city: 10, district: "林園區" },
  { id: 122, city: 10, district: "岡山區" },
  { id: 123, city: 10, district: "茄萣區" },
  { id: 124, city: 10, district: "烏松區" },
  { id: 125, city: 10, district: "大寮區" },
  { id: 126, city: 10, district: "橋頭區" },
  { id: 127, city: 10, district: "湖內區" },
  { id: 128, city: 10, district: "大社區" },
  { id: 129, city: 10, district: "彌陀區" },
  { id: 130, city: 10, district: "路竹區" },
  { id: 131, city: 10, district: "阿蓮區" },
  { id: 132, city: 10, district: "大樹區" },
  { id: 133, city: 10, district: "永安區" },
  { id: 134, city: 10, district: "燕巢區" },
  { id: 135, city: 10, district: "旗山區" },
  { id: 136, city: 10, district: "美濃區" },
  { id: 137, city: 10, district: "甲仙區" },
  { id: 138, city: 11, district: "屏東市" },
  { id: 139, city: 11, district: "東港鎮" },
  { id: 140, city: 11, district: "恆春鎮" },
  { id: 141, city: 11, district: "潮州鎮" },
  { id: 142, city: 11, district: "竹田鄉" },
  { id: 143, city: 11, district: "車城鄉" },
  { id: 144, city: 11, district: "麟洛鄉" },
];

export const columns = ["縣市", "區域", "站點名稱", "可借車輛", "可還空位"];
