export const citys = [
  { id: 1, city: "台北市" },
  { id: 2, city: "新北市" },
  { id: 3, city: "新竹縣" },
  { id: 4, city: "新竹市" },
  { id: 5, city: "新竹科學園區" },
  { id: 6, city: "苗栗縣" },
  { id: 7, city: "台中市" },
  { id: 8, city: "嘉義市" },
  { id: 9, city: "台南市" },
  { id: 10, city: "高雄市" },
  { id: 11, city: "屏東縣" },
];

export const options = [
  { id: 1, city: "台北市", district: "松山區", checked: true },
  { id: 2, city: "台北市", district: "信義區", checked: true },
  { id: 3, city: "台北市", district: "大安區", checked: true },
  { id: 4, city: "台北市", district: "中山區", checked: true },
  { id: 5, city: "台北市", district: "中正區", checked: true },
  { id: 6, city: "台北市", district: "大同區", checked: true },
  { id: 7, city: "台北市", district: "萬華區", checked: true },
  { id: 8, city: "台北市", district: "文山區", checked: true },
  { id: 9, city: "台北市", district: "南港區", checked: true },
  { id: 10, city: "台北市", district: "內湖區", checked: true },
  { id: 11, city: "台北市", district: "士林區", checked: true },
  { id: 12, city: "台北市", district: "北投區", checked: true },
  { id: 13, city: "新北市", district: "八里區", checked: true },
  { id: 14, city: "新北市", district: "三芝區", checked: true },
  { id: 15, city: "新北市", district: "三重區", checked: true },
  { id: 16, city: "新北市", district: "三峽區", checked: true },
  { id: 17, city: "新北市", district: "土城區", checked: true },
  { id: 18, city: "新北市", district: "中和區", checked: true },
  { id: 19, city: "新北市", district: "五股區", checked: true },
  { id: 20, city: "新北市", district: "永和區", checked: true },
  { id: 21, city: "新北市", district: "石門區", checked: true },
  { id: 22, city: "新北市", district: "石碇區", checked: true },
  { id: 23, city: "新北市", district: "汐止區", checked: true },
  { id: 24, city: "新北市", district: "金山區", checked: true },
  { id: 25, city: "新北市", district: "林口區", checked: true },
  { id: 26, city: "新北市", district: "坪林區", checked: true },
  { id: 27, city: "新北市", district: "板橋區", checked: true },
  { id: 28, city: "新北市", district: "泰山區", checked: true },
  { id: 29, city: "新北市", district: "淡水區", checked: true },
  { id: 30, city: "新北市", district: "深坑區", checked: true },
  { id: 31, city: "新北市", district: "萬里區", checked: true },
  { id: 32, city: "新北市", district: "瑞芳區", checked: true },
  { id: 33, city: "新北市", district: "新店區", checked: true },
  { id: 34, city: "新北市", district: "新莊區", checked: true },
  { id: 35, city: "新北市", district: "樹林區", checked: true },
  { id: 36, city: "新北市", district: "雙溪區", checked: true },
  { id: 37, city: "新北市", district: "蘆洲區", checked: true },
  { id: 38, city: "新北市", district: "鶯歌區", checked: true },
  { id: 39, city: "新竹縣", district: "竹北市", checked: true },
  { id: 40, city: "新竹縣", district: "竹東鎮", checked: true },
  { id: 41, city: "新竹縣", district: "湖口鄉", checked: true },
  { id: 42, city: "新竹縣", district: "新豐鄉", checked: true },
  { id: 43, city: "新竹市", district: "東區", checked: true },
  { id: 44, city: "新竹市", district: "北區", checked: true },
  { id: 45, city: "新竹市", district: "香山區", checked: true },
  { id: 46, city: "新竹科學園區", district: "新竹科學園區", checked: true },
  { id: 47, city: "苗栗縣", district: "竹南鎮", checked: true },
  { id: 48, city: "苗栗縣", district: "苑裡鎮", checked: true },
  { id: 49, city: "台中市", district: "中區", checked: true },
  { id: 50, city: "台中市", district: "東區", checked: true },
  { id: 51, city: "台中市", district: "西區", checked: true },
  { id: 52, city: "台中市", district: "南區", checked: true },
  { id: 53, city: "台中市", district: "北區", checked: true },
  { id: 54, city: "台中市", district: "西屯區", checked: true },
  { id: 55, city: "台中市", district: "南屯區", checked: true },
  { id: 56, city: "台中市", district: "北屯區", checked: true },
  { id: 57, city: "台中市", district: "豐原區", checked: true },
  { id: 58, city: "台中市", district: "大里區", checked: true },
  { id: 59, city: "台中市", district: "太平區", checked: true },
  { id: 60, city: "台中市", district: "清水區", checked: true },
  { id: 61, city: "台中市", district: "沙鹿區", checked: true },
  { id: 62, city: "台中市", district: "大甲區", checked: true },
  { id: 63, city: "台中市", district: "東勢區", checked: true },
  { id: 64, city: "台中市", district: "梧棲區", checked: true },
  { id: 65, city: "台中市", district: "烏日區", checked: true },
  { id: 66, city: "台中市", district: "神岡區", checked: true },
  { id: 67, city: "台中市", district: "大肚區", checked: true },
  { id: 68, city: "台中市", district: "大雅區", checked: true },
  { id: 69, city: "台中市", district: "后里區", checked: true },
  { id: 70, city: "台中市", district: "霧峰區", checked: true },
  { id: 71, city: "台中市", district: "潭子區", checked: true },
  { id: 72, city: "台中市", district: "龍井區", checked: true },
  { id: 73, city: "台中市", district: "外埔區", checked: true },
  { id: 74, city: "台中市", district: "和平區", checked: true },
  { id: 75, city: "台中市", district: "石岡區", checked: true },
  { id: 76, city: "台中市", district: "大安區", checked: true },
  { id: 77, city: "台中市", district: "新社區", checked: true },
  { id: 78, city: "嘉義市", district: "市區", checked: true },
  { id: 79, city: "台南市", district: "七股區", checked: true },
  { id: 80, city: "台南市", district: "下營區", checked: true },
  { id: 81, city: "台南市", district: "山上區", checked: true },
  { id: 82, city: "台南市", district: "中西區", checked: true },
  { id: 83, city: "台南市", district: "仁德區", checked: true },
  { id: 84, city: "台南市", district: "六甲區", checked: true },
  { id: 85, city: "台南市", district: "北門區", checked: true },
  { id: 86, city: "台南市", district: "北區", checked: true },
  { id: 87, city: "台南市", district: "永康區", checked: true },
  { id: 88, city: "台南市", district: "玉井區", checked: true },
  { id: 89, city: "台南市", district: "白河區", checked: true },
  { id: 90, city: "台南市", district: "安平區", checked: true },
  { id: 91, city: "台南市", district: "安南區", checked: true },
  { id: 92, city: "台南市", district: "佳里區", checked: true },
  { id: 93, city: "台南市", district: "官田區", checked: true },
  { id: 94, city: "台南市", district: "東山區", checked: true },
  { id: 95, city: "台南市", district: "東區", checked: true },
  { id: 96, city: "台南市", district: "南區", checked: true },
  { id: 97, city: "台南市", district: "後壁區", checked: true },
  { id: 98, city: "台南市", district: "柳營區", checked: true },
  { id: 99, city: "台南市", district: "麻豆區", checked: true },
  { id: 100, city: "台南市", district: "善化區", checked: true },
  { id: 101, city: "台南市", district: "新化區", checked: true },
  { id: 102, city: "台南市", district: "新市區", checked: true },
  { id: 103, city: "台南市", district: "新營區", checked: true },
  { id: 104, city: "台南市", district: "歸仁區", checked: true },
  { id: 105, city: "台南市", district: "關廟區", checked: true },
  { id: 106, city: "台南市", district: "鹽水區", checked: true },
  { id: 107, city: "高雄市", district: "新興區", checked: true },
  { id: 108, city: "高雄市", district: "苓雅區", checked: true },
  { id: 109, city: "高雄市", district: "三民區", checked: true },
  { id: 110, city: "高雄市", district: "鹽埕區", checked: true },
  { id: 111, city: "高雄市", district: "前金區", checked: true },
  { id: 112, city: "高雄市", district: "鳳山區", checked: true },
  { id: 113, city: "高雄市", district: "左營區", checked: true },
  { id: 114, city: "高雄市", district: "前鎮區", checked: true },
  { id: 115, city: "高雄市", district: "鼓山區", checked: true },
  { id: 116, city: "高雄市", district: "楠梓區", checked: true },
  { id: 117, city: "高雄市", district: "旗津區", checked: true },
  { id: 118, city: "高雄市", district: "小港區", checked: true },
  { id: 119, city: "高雄市", district: "梓官區", checked: true },
  { id: 120, city: "高雄市", district: "仁武區", checked: true },
  { id: 121, city: "高雄市", district: "林園區", checked: true },
  { id: 122, city: "高雄市", district: "岡山區", checked: true },
  { id: 123, city: "高雄市", district: "茄萣區", checked: true },
  { id: 124, city: "高雄市", district: "烏松區", checked: true },
  { id: 125, city: "高雄市", district: "大寮區", checked: true },
  { id: 126, city: "高雄市", district: "橋頭區", checked: true },
  { id: 127, city: "高雄市", district: "湖內區", checked: true },
  { id: 128, city: "高雄市", district: "大社區", checked: true },
  { id: 129, city: "高雄市", district: "彌陀區", checked: true },
  { id: 130, city: "高雄市", district: "路竹區", checked: true },
  { id: 131, city: "高雄市", district: "阿蓮區", checked: true },
  { id: 132, city: "高雄市", district: "大樹區", checked: true },
  { id: 133, city: "高雄市", district: "永安區", checked: true },
  { id: 134, city: "高雄市", district: "燕巢區", checked: true },
  { id: 135, city: "高雄市", district: "旗山區", checked: true },
  { id: 136, city: "高雄市", district: "美濃區", checked: true },
  { id: 137, city: "高雄市", district: "甲仙區", checked: true },
  { id: 138, city: "屏東縣", district: "屏東市", checked: true },
  { id: 139, city: "屏東縣", district: "東港鎮", checked: true },
  { id: 140, city: "屏東縣", district: "恆春鎮", checked: true },
  { id: 141, city: "屏東縣", district: "潮州鎮", checked: true },
  { id: 142, city: "屏東縣", district: "竹田鄉", checked: true },
  { id: 143, city: "屏東縣", district: "車城鄉", checked: true },
  { id: 144, city: "屏東縣", district: "麟洛鄉", checked: true },
];

export const columns = ["縣市", "區域", "站點名稱", "可借車輛", "可還空位"];
